### ISSUE TITLE
OctoPrint support incompatible with SuperSlicer

### ISSUE THREAD

**Issue by cloakedcode** [Arksine/moonraker#112] opened 2021-03-06 06:12 UTC
I've enabled the new OctoPrint API support with `[octoprint_compat]` and now get this in SuperSlicer:

![image](https://user-images.githubusercontent.com/177435/110197270-77d9a800-7e18-11eb-9663-9fb96b07533f.png)

Fluidd lists Moonraker version `v0.3.1-42 `. I will likely downgrade while this issue is resolved to make my printer usable again.

Out of curiosity, are there Moonraker features that will make the slicer integration better than what the OctoPrint (compatible) API provides?

Edit: I should note SuperSlicer was able to upload through the same method yesterday or the day before (Moonraker was up-to-date as of Thursday night IIRC).

**Comment by zellneralex** [comment] 2021-03-06 06:46
See https://github.com/Arksine/moonraker/issues/111

**Comment by Arksine** [comment] 2021-03-06 10:52
What version of SuperSlicer is this?  I can confirm that uploads work with 2.2.53.  I can also confirm PrusaSlicer 2.3.0 works.

Please include moonraker.log.  My guess is that you added `[octorpint_compat]` without restarting the server.

**Comment by Turge08** [comment] 2021-03-06 17:05
I'm having the same issue with PrusaSlicer after updating Moonraker.

![image](https://user-images.githubusercontent.com/6312320/110214774-252dd980-7e74-11eb-9fff-8698d47d66a2.png)

This was working earlier yesterday.

**Comment by Arksine** [comment] 2021-03-06 17:46
Yes, adding `[octoprint_compat]` and restarting the moonraker service should resolve your problems.  If you could report back that it is resolved would appreciate it.

**Comment by Turge08** [comment] 2021-03-06 17:47
> Yes, adding `[octoprint_compat]` and restarting the moonraker service should resolve your problems. If you could report back that it is resolved would appreciate it.

Yup it works after adding the entry to moonraker.conf and restarting moonraker. 

Thanks!

**Comment by cloakedcode** [comment] 2021-03-06 19:41
Very strange... I swear Fluidd restarted Moonraker when I edited the conf and hit the "Save & Restart" button. This time updating, adding `[octoprint_compat],` and hitting that same button resulted in SuperSlicer complaining with 403 Forbidden code. Oddly the log indicates the IP is detected as trusted but then later responds with 403 to that same IP. Restarting the service again (this time with the circular arrow restart button in Fluidd's sidebar) fixed the issue.

I've attached the logs. Should I open a separate issue for this? Is there a restart API endpoint that is possibly not doing a full tear down or something? It seems odd that I've run into several issues involving restarts that were fixed by subsequent restart.
[moonraker(3).log](https://github.com/Arksine/moonraker/files/6095972/moonraker.3.log)

**Comment by Arksine** [comment] 2021-03-06 19:48
You got a forbidden error because Klipper had the file loaded.  Moonraker will refuse to overwrite the file in this scenario.

**Comment by Arksine** [comment] 2021-03-06 19:50
Hmm, looking closer, Klippy doesn't appear to be connected.  Let me investigate this further.

**Comment by cloakedcode** [comment] 2021-03-06 19:56
Klipper loads all the *.conf files, not just printer.conf? Why is Klipper touching moonraker.conf?

**Comment by Arksine** [comment] 2021-03-06 22:19
You have it.  However I may modify the check in Moonraker to allow the file to be overwritten if Klippy is in the `shutdown` state.  Even though Klippy reports as having a the file loaded, it really doesn't when its shutdown.

**Comment by Arksine** [comment] 2021-04-20 23:47
I'm going to close this as it should be resolved.

**Closed by Arksine** 2021-04-20 23:47 UTC
