### ISSUE TITLE
Building wheel for streaming-form-data (pyproject.toml) ... error

### ISSUE THREAD

**Issue by dflstone** [Arksine/moonraker#724] opened 2023-10-10 13:28 UTC
### What happened

Building wheels for collected packages: streaming-form-data
  Building wheel for streaming-form-data (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for streaming-form-data (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/streaming_form_data
      copying streaming_form_data/validators.py -> build/lib.linux-aarch64-cpython-311/streaming_form_data
      copying streaming_form_data/targets.py -> build/lib.linux-aarch64-cpython-311/streaming_form_data
      copying streaming_form_data/parser.py -> build/lib.linux-aarch64-cpython-311/streaming_form_data
      copying streaming_form_data/__init__.py -> build/lib.linux-aarch64-cpython-311/streaming_form_data
      running build_ext
      building 'streaming_form_data._parser' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/streaming_form_data
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/orangepi/moonraker-env/include -I/usr/include/python3.11 -c streaming_form_data/_parser.c -o build/temp.linux-aarch64-cpython-311/streaming_form_data/_parser.o
      streaming_form_data/_parser.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for streaming-form-data
Failed to build streaming-form-data
ERROR: Could not build wheels for streaming-form-data, which is required to install pyproject.toml-based projects

### Client

Mainsail

### Browser

Microsoft Edge

### How to reproduce

kiauh install moonraker

**Comment by dflstone** [comment] 2023-10-10 13:29
___  ____ ___   _____             ____  
 / _ \|  _ \_ _| |__  /___ _ __ ___|___ \ 
| | | | |_) | |    / // _ \ '__/ _ \ __) |
| |_| |  __/| |   / /|  __/ | | (_) / __/ 
 \___/|_|  |___| /____\___|_|  \___/_____|
                                          
Welcome to Orange Pi 3.1.0 Bookworm with Linux 6.1.31-sun50iw9

System load:   25%           	Up time:       2:16	Local users:   2            	
Memory usage:  16% of 981M   	IP:	       192.168.50.219
CPU temp:      43°C           	Usage of /:    24% of 15G

**Comment by Arksine** [comment] 2023-10-15 17:50
This issue *might* be resolved by fd11c08b999ab9cc188ad1c933a6e19953912c6b.  The problem is not with Moonraker, but with the linux image on your system.  Its missing the requirements necessary to build one of Moonraker's dependencies.  Hopefully updating the version will fix it, but if not then there isn't much that can be done in the near term.

**Comment by dflstone** [comment] 2023-10-17 14:04
i tryed it in armbian 6.1, It worked！thank you!

**Closed** 2023-10-17 14:04 UTC
