### ISSUE TITLE
MQTT power switch doesn't reflect actual state

### ISSUE THREAD

**Issue by Stooovie** [Arksine/moonraker#719] opened 2023-10-03 08:22 UTC
### What happened

I have added a MQTT power switch from Home Assistant that controls power to the printer. I can turn the printer on and off fine, but the actual switch in Klipper (both Fluidd and Mainsail) does not reflect the actual state of the switch until I toggle it. In other words, it's displayed as "turned on" even when the switch is off. So, to turn the printer actually on, I have to first toggle the switch to "off" and to "on" again.

The switch state in HA is always correct.

### Client

Mainsail, Fluidd, MobileRaker

### Browser

Other or N/A

### How to reproduce

1) add a MQTT power switch from HA into moonraker
2) it will not accurately report state

### Additional information

[power EnderPlug]
type: homeassistant
address: REDACTED
port: 8123
device: switch.ender_plug
token: REDACTED
domain: switch
on_when_job_queued: True

**Comment by Arksine** [comment] 2023-10-05 12:21
This is a duplicate of #703.  While the swtich may be configured to use mqtt in Home Assistant, Moonraker communicates with Home Assistant over http.  The only way for Moonraker to detect changes made to http switches would be to poll the switch status.  Currently this isn't supported.  Adding support for polling isn't off the table, but introduces some challenges with some of Moonraker's other switch functionality, so I have no timeline as to when it will be added.

For what its worth, if the switch operates over MQTT it is also possible to configure a `mqtt` type switch in Moonraker.  MQTT switches have state pushed to them, thus they can accurately reflect changes made outside of Moonarker.

**Closed by Arksine** 2023-10-05 12:21 UTC
Labels: bug, duplicate
