### ISSUE TITLE
Error on Moonraker startup with Spoolman

### ISSUE THREAD

**Issue by gfosdike1** [Arksine/moonraker#811] opened 2024-02-14 23:30 UTC
### What happened

After a full update my printer I get the attached error

![image](https://github.com/Arksine/moonraker/assets/88576109/7555bc49-0932-4a0b-bae6-ff614e708520)

### Client

Mainsail

### Browser

Chrome

### How to reproduce

On every start of Mainsail/Moonraker

### Additional information

[moonraker (5).log](https://github.com/Arksine/moonraker/files/14289573/moonraker.5.log)

**Comment by Arksine** [comment] 2024-02-15 01:28
This is in part a duplicate of #810.  The error message requires a fix in mainsail.  I believe it has been applied but not yet released.

Separately, Moonraker is receiving a 403 "Forbidden" error when attempting to connect to spoolman's websocket.  This is an issue with the spoolman instance that needs to be corrected.

**Comment by gfosdike1** [comment] 2024-02-15 16:14
It looks like the cause of the 403 is Moonraker. I can curl to the IP and port without issue direct from the OS:

pi@mainsailos:~ $ curl http://192.168.0.39:7912
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#DC7734" />
    <meta name="description" content="Spoolman UI" />
    <meta name="robots" content="noindex,nofollow" />
    <title>Spoolman</title>
    <script type="module" crossorigin src="/assets/index-8f7a88d5.js"></script>
    <link rel="stylesheet" href="/assets/index-c7b46f6e.css">
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

  </body>
</html>

Docker log shows the following:
2024-02-15 16:09:07 spoolman-1  | INFO:     172.18.0.1:36630 - "GET / HTTP/1.1" 200 OK

**Comment by Arksine** [comment] 2024-02-15 16:44
403 is the response Moonraker receives from spoolman.  Why its forbidden on your instance I am not sure, as its available to me.

You are using curl to request the interface, Moonraker is getting a 403 when attempting to connect to the websocket.  If you want to try from the command line you can use wscat:

```
sudo apt install node-ws
wscat -c ws://192.168.0.39:7912/api/v1/spool
```

**Closed** 2024-02-16 10:28 UTC
Labels: duplicate, user help request
