### ISSUE TITLE
MQTT publish - only webhooks get published

### ISSUE THREAD

**Issue by kolbenhans** [Arksine/moonraker#255] opened 2021-10-27 13:29 UTC
I already tried a lot of different configurations, but the only mqtt publish thats seems to work is the webhook data.

moonraker.conf
```
[mqtt]
address: 192.168.0.27
port: 1883
username: sticky
password_file: ~/.mrpwd
instance_name: moonraker
status_objects:
  webhooks
  print_stats
  extruder=temperature
  heater_bed=temperature,target

```
mqtt published:
`{"eventtime": 423824.53180501, "status": {"webhooks": {"state": "ready", "state_message": "Printer is ready"}}}`

i also put webhooks at the end of the list, still only webhooks got reported.

**Comment by pedrolamas** [comment] 2021-11-05 16:40
I'm tried with `webhooks` and `print_stats` only and did see results appearing, but that was before the changes to allow field filtering...

I will try and check this again later on the weekend and confirm if I can repro this issue.

**Comment by Arksine** [comment] 2021-11-05 21:06
FWIW, I can't reproduce.  If its still an issue providing both klippy.log and moonraker.log might provide some insight.

**Comment by pedrolamas** [comment] 2021-11-26 09:55
Can't repro either, seems to be working fine!

**Comment by Arksine** [comment] 2021-12-22 12:54
As there has been no further discussion I'm going to close this issue.  If the problem remains you may reopen, however please upload the logs as instructed above.

**Closed by Arksine** 2021-12-22 12:54 UTC
