### ISSUE TITLE
Updated Moonraker and now cannot connect

### ISSUE THREAD

**Issue by turbotrix** [Arksine/moonraker#353] opened 2022-01-30 17:13 UTC
### What happened

this is what i got back

 sudo journalctl -xe -u moonraker.service
[sudo] password for pi:
Jan 30 16:59:22 mainsailos python[2634]:     server = Server(app_args, file_logg
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     self._load_components(config)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     self.load_component(config, compone
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     raise ServerError(msg)
Jan 30 16:59:22 mainsailos python[2634]: utils.ServerError: Unable to load compo
Jan 30 16:59:22 mainsailos python[2634]: [moonraker.py:main()] - Server Shutdown
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Main process exited, c
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Failed with result 'ex
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-c
lines 1343-1365/1365 (END)
Jan 30 16:59:22 mainsailos python[2634]:     server = Server(app_args, file_logger, event_loop)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 152, in __init__
Jan 30 16:59:22 mainsailos python[2634]:     self._load_components(config)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 230, in _load_components
Jan 30 16:59:22 mainsailos python[2634]:     self.load_component(config, component)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 257, in load_component
Jan 30 16:59:22 mainsailos python[2634]:     raise ServerError(msg)
Jan 30 16:59:22 mainsailos python[2634]: utils.ServerError: Unable to load component: (dbus_manager)
Jan 30 16:59:22 mainsailos python[2634]: [moonraker.py:main()] - Server Shutdown
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-code'.

### Client

Mainsail

### Browser

Chrome

### How to reproduce

updated moonraker

### Additional information

 sudo journalctl -xe -u moonraker.service
[sudo] password for pi:
Jan 30 16:59:22 mainsailos python[2634]:     server = Server(app_args, file_logg
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     self._load_components(config)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     self.load_component(config, compone
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/mo
Jan 30 16:59:22 mainsailos python[2634]:     raise ServerError(msg)
Jan 30 16:59:22 mainsailos python[2634]: utils.ServerError: Unable to load compo
Jan 30 16:59:22 mainsailos python[2634]: [moonraker.py:main()] - Server Shutdown
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Main process exited, c
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Failed with result 'ex
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit moonraker.service has entered the 'failed' state with result 'exit-c
lines 1343-1365/1365 (END)
Jan 30 16:59:22 mainsailos python[2634]:     server = Server(app_args, file_logger, event_loop)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 152, in __init__
Jan 30 16:59:22 mainsailos python[2634]:     self._load_components(config)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 230, in _load_components
Jan 30 16:59:22 mainsailos python[2634]:     self.load_component(config, component)
Jan 30 16:59:22 mainsailos python[2634]:   File "/home/pi/moonraker/moonraker/moonraker.py", line 257, in load_component
Jan 30 16:59:22 mainsailos python[2634]:     raise ServerError(msg)
Jan 30 16:59:22 mainsailos python[2634]: utils.ServerError: Unable to load component: (dbus_manager)
Jan 30 16:59:22 mainsailos python[2634]: [moonraker.py:main()] - Server Shutdown
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit moonraker.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Jan 30 16:59:22 mainsailos systemd[1]: moonraker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support

**Comment by Arksine** [comment] 2022-01-30 17:16
Closing this as a duplicate of #352.

**Closed by Arksine** 2022-01-30 17:16 UTC
Labels: bug
